// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZvu5YaC-3gsJpDvAKPze_JNVWIiGLBA',
    appId: '1:161367488776:web:9336417bf9cf2f8f4454bd',
    messagingSenderId: '161367488776',
    projectId: 'w-safe-83af7',
    authDomain: 'w-safe-83af7.firebaseapp.com',
    storageBucket: 'w-safe-83af7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEa9ejwMviFtIPOVSUDtaZ-kVAitdPA8g',
    appId: '1:161367488776:android:45e5d67b72e4aebe4454bd',
    messagingSenderId: '161367488776',
    projectId: 'w-safe-83af7',
    storageBucket: 'w-safe-83af7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDFr4TPaqncKTnGCrBFKSzhTA2ua0oZwI',
    appId: '1:161367488776:ios:4c82ff1b0b0570264454bd',
    messagingSenderId: '161367488776',
    projectId: 'w-safe-83af7',
    storageBucket: 'w-safe-83af7.appspot.com',
    iosClientId: '161367488776-lcnbt6h02u19rlm21v2um1p3d8mmkfff.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinanceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDFr4TPaqncKTnGCrBFKSzhTA2ua0oZwI',
    appId: '1:161367488776:ios:4c82ff1b0b0570264454bd',
    messagingSenderId: '161367488776',
    projectId: 'w-safe-83af7',
    storageBucket: 'w-safe-83af7.appspot.com',
    iosClientId: '161367488776-lcnbt6h02u19rlm21v2um1p3d8mmkfff.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFinanceApp',
  );
}
